# Generated by Django 3.0.5 on 2020-05-06 15:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forum', '0008_auto_20200505_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.URLField(default='https://www.w3schools.com/w3images/avatar6.png', max_length=300),
        ),
        migrations.AlterField(
            model_name='topic',
            name='followers',
            field=models.ManyToManyField(blank=True, related_name='topic_followers', to=settings.AUTH_USER_MODEL),
        ),
    ]
