# Generated by Django 3.0.5 on 2020-05-13 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0011_auto_20200511_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.URLField(blank=True, max_length=400),
        ),
        migrations.AlterField(
            model_name='post',
            name='video',
            field=models.URLField(blank=True, max_length=400),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.URLField(default='https://www.w3schools.com/w3images/avatar6.png', max_length=400),
        ),
    ]
